name: gr_lrr
description: A application for controlling GR-LRR devices.

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.1+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  web_socket_channel: ^3.0.1
  package_info_plus: ^8.0.2
  provider: ^6.0.5
  get_ip_address: ^0.0.6
  fl_chart: ^0.68.0
  audioplayers: ^6.0.0

  flutter_localizations:
    sdk: flutter
  http: ^1.1.0
  list_utilities: ^1.0.3


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/

flutter_icons:
  android: "launcher_icon"
  ios: false
  image_path: "assets/images/vestas.png"
