name: gr_lrr
description: A application for controlling GR-LRR devices.

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.1+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  web_socket_channel: ^2.1.0
  package_info_plus: ^4.1.0
  provider: ^6.0.5
  get_ip_address: ^0.0.6
  fl_chart: ^0.41.0
  audioplayers: ^5.2.1

  flutter_localizations:
    sdk: flutter


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
